security:
  jwt:
    secret: ${JWT_SECRET:dev-secret-key-minimum-32-characters-long}
    expiration-ms: ${JWT_EXPIRATION_MS:900000} # 15 minutes
spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes en ms
      cache-null-values: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 0.0.1-SNAPSHOT
    description: Production-grade REST service — Cloud-Native Engineering Sandbox

logging:
  level:
    root: INFO
    com.zatadev: DEBUG