apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Cloud overrides for EKS
# Images pulled from GitLab Container Registry
images:
  - name: user-service:local
    newName: registry.gitlab.com/zatadev/engineering-sandbox/user-service
    newTag: latest
  - name: order-service:local
    newName: registry.gitlab.com/zatadev/engineering-sandbox/order-service
    newTag: latest
  - name: notification-service:local
    newName: registry.gitlab.com/zatadev/engineering-sandbox/notification-service
    newTag: latest