apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: sandbox-infra
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
data:
  POSTGRES_DB: userdb
  POSTGRES_USER: sandbox